Fresh Farm Market/Pages/Changepassword.cshtml.cs
using Fresh_Farm_Market.Model;
using Fresh_Farm_Market.Service;
using Fresh_Farm_Market.ViewModel;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Routing;
using MimeKit;
using System.Web;
using static System.Net.WebRequestMethods;

namespace Fresh_Farm_Market.Pages
{
    public class Index1Model : PageModel
        
    {
        private UserManager<User> userManager { get; }
        private readonly IConfiguration _config;

        [BindProperty]
        public Changepassword Changepassword { get; set; }

        public Index1Model(UserManager<User> usermanager, IConfiguration config)
        {
            this.userManager = usermanager;
            _config = config;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var user = await userManager.FindByEmailAsync(HttpUtility.HtmlEncode(Changepassword.EmailAddress));
            if (user == null)
            {
                ModelState.AddModelError("", "Email does not exist");
                return Page();
            }

            DateTime userdate = user.PasswordDay;
            DateTime current = DateTime.Now;
            int resilt = DateTime.Compare(current, userdate.AddSeconds(user.MinimumPasswordAge));
            if (resilt > 0)
            {


                var token = await userManager.GeneratePasswordResetTokenAsync(user);
                var url = Url.PageLink("/ResetPassword", values: new { email = Changepassword.EmailAddress, token = token });
                var email = new MimeMessage();
                email.From.Add(new MailboxAddress("Forget Password", "aikleong0713@gmail.com"));
                email.To.Add(new MailboxAddress("User", user.Email));
                email.Subject = "Forget Password";
                email.Body = new TextPart("plain") { Text = url };

                using (var smtp = new SmtpClient())
                {
                    smtp.Connect("smtp.gmail.com", 587, false);
                    smtp.Authenticate(_config["Gmail:Email"], _config["Gmail:AppPassword"]);
                    smtp.Send(email);
                    smtp.Disconnect(true);
                }

                return Page();
            }
            else
            {
                ModelState.AddModelError("", "Minimum Password Age limit has not reached you are not allowed to change password");
                return Page();
            }
            return Page();
        }

    }
}

Fresh Farm Market/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Fresh_Farm_Market.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Fresh Farm Market/Pages/GoogleUser.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Fresh_Farm_Market.Pages
{
    [Authorize(Roles ="Google")]
    public class GoogleUserModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Fresh Farm Market/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity;
using Fresh_Farm_Market.Model;
using Microsoft.AspNetCore.DataProtection;

namespace Fresh_Farm_Market.Pages
{
    [Authorize(Roles = "Customer, Google")]

    [AutoValidateAntiforgeryToken]
    public class IndexModel : PageModel
    {
        private readonly UserManager<User> userManager;
        public User user { get; set; }
        public string imgsrc { get;set; }
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger, UserManager<User> userManager)
        {
            _logger = logger;
            this.userManager = userManager;
           
        }

        public async Task<IActionResult> OnGet()
        {

            var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
            var protector = dataProtectionProvider.CreateProtector("MySecretKey");
            user = await userManager.FindByIdAsync(userManager.GetUserId(User));
            user.CreditCard = protector.Unprotect(user.CreditCard);
            imgsrc = "../uploads/" + user.Id + ".jpg";
            
            //if (HttpContext.Session.GetString("SessionTimeout") == null)
            //{
            //    return RedirectToPage("Login");
            //}
            return Page();
            //user.CreditCard = "ABC";
        }
    }
}

Fresh Farm Market/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Fresh_Farm_Market.ViewModel;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Fresh_Farm_Market.Model;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using GoogleReCaptcha.V3;
using GoogleReCaptcha.V3.Interface;
using Fresh_Farm_Market.Models;
using System.Web;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Text.Json;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Fresh_Farm_Market.Service;

namespace Fresh_Farm_Market.Pages
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public Login LModel { get; set; }

        private UserManager<User> userManager { get; }
        private AuditLogService auditLog { get; set; }
        private SignInManager<User> signInManager { get; }
        private readonly reCaptchaService _reCaptchaService;
        public LoginModel(UserManager<User> userManager, SignInManager<User> signInManager, reCaptchaService reCaptchaService,AuditLogService auditLogService)
        {
            this.auditLog = auditLogService;
            _reCaptchaService = reCaptchaService;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        public void OnGet()
        {

        }

        public IActionResult OnPostLoginG()
        {
            string redirectUrl = "/Google";

            var properties = signInManager.ConfigureExternalAuthenticationProperties("Google", redirectUrl);
            
            return new ChallengeResult("Google", properties);
        }

          
        
            
            //var result = await HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);
           
            //var claims = result.Principal.Identities.FirstOrDefault().Claims.Select(claim => new
            //{
            //    claim.Issuer,
            //    claim.OriginalIssuer,
            //    claim.Type,
            //    claim.Value
               
            //});
            //return JsonSerializer.Serialize(claims);

        public async Task<IActionResult> OnPostAsync()
            
        {

            var reCaptcharesult = _reCaptchaService.tokenVerify(LModel.token);
            if (!reCaptcharesult.Result.success || reCaptcharesult.Result.score <= 0.5)
            {
                ModelState.AddModelError("", "you are not a human.");
                return Page();

            }
            if (ModelState.IsValid)
            {
                var identityResult = await signInManager.PasswordSignInAsync(LModel.Email, LModel.Password, LModel.RememberMe, true);
                if (identityResult.IsLockedOut)
                {
                    ModelState.AddModelError("", "Account is locked out");
                    return Page();
                }
                if (identityResult.Succeeded)
                {
                    var user = await userManager.FindByEmailAsync(LModel.Email);
                    if (user != null)
                    {
                        DateTime current = DateTime.Now;
                        DateTime userMax = user.PasswordDay.AddDays(user.MaximumPasswordAge);
                        int result = DateTime.Compare(userMax, current);
                       
                        if (result <= 0)
                        {
                            ModelState.AddModelError("", "Maximum Password Age reached password need to be reset");
                            return Page();
                        }
                        var audit = new AuditLog()
                        {
                            Id = Guid.NewGuid().ToString(),
                            userId = user.Id,
                            Activity = "Logged In",
                            DateTime = DateTime.Now
                        };
                        auditLog.AddAudit(audit);
                        return RedirectToPage("Index");
                    }


                    
                }


                ModelState.AddModelError("", "Username or Password incorrect");
            }
            return Page();
        }
    }
}

Fresh Farm Market/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Fresh_Farm_Market.Model;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authentication;
using Fresh_Farm_Market.Models;
using Fresh_Farm_Market.Service;

namespace Fresh_Farm_Market.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<User> signInManager;
        private readonly AuditLogService auditLog;
        private readonly UserManager<User> userManager;
        public LogoutModel(SignInManager<User> signInManager, UserManager<User> userManager, AuditLogService auditLogService)
        {
            this.auditLog = auditLogService;
          
            this.signInManager = signInManager;
            this.userManager = userManager;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            var audit = new AuditLog()
            {
                Id = Guid.NewGuid().ToString(),
                userId = userManager.GetUserId(User),
                Activity = "Logged Out",
                DateTime = DateTime.Now
            };
            auditLog.AddAudit(audit);
            await signInManager.SignOutAsync();
            await HttpContext.SignOutAsync();
            HttpContext.Session.Clear();
            return RedirectToPage("Login");
        }

        public async Task<IActionResult> OnPostDontLogoutAsync()
        {
            return RedirectToPage("Index");
        }
    }
}

Fresh Farm Market/Pages/MFA.cshtml.cs
using Fresh_Farm_Market.Model;
using Fresh_Farm_Market.ViewModel;
using MailKit.Net.Smtp;
using MailKit.Security;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MimeKit;
using MimeKit.Text;


namespace Fresh_Farm_Market.Pages
{
    [Authorize]
    public class Mfa : PageModel
    {
        
        [BindProperty]
        public MFA mfa { get; set; }
        private readonly IConfiguration _config;
        private UserManager<User> userManager { get; }

        public Mfa(UserManager<User> userManager, IConfiguration config)
        {

            this.userManager = userManager;
            _config = config;
        }
        private Random _random = new Random();

        public string GenerateRandomNo()
        {
            return _random.Next(0, 9999).ToString("D4");
        }
        public async Task<IActionResult> OnGet()
        {
            var user = await userManager.FindByEmailAsync(User.Identity.Name);
            var email = new MimeMessage();
            var otp = GenerateRandomNo();
            user.OTP = otp;
            user.OTPdateTime = DateTime.Now;
            await userManager.UpdateAsync(user);
            email.From.Add(new MailboxAddress("TEST", _config["Gmail:Email"]));
            email.To.Add(new MailboxAddress("User",user.Email));
            email.Subject = "Authentication";
            email.Body = new TextPart("plain") { Text = otp };
            
            using (var smtp = new SmtpClient())
            {
                smtp.Connect("smtp.gmail.com", 587, false);
                smtp.Authenticate(_config["Gmail:Email"], _config["Gmail:AppPassword"]);
                smtp.Send(email);
                smtp.Disconnect(true);
            }
            return Page();
               
        }
        public async Task<IActionResult> OnPostResend()
        {
            
            User user = await userManager.FindByEmailAsync(HttpContext.User.Identity.Name);

            var email = new MimeMessage();
            var otp = GenerateRandomNo();
            user.OTP = "1323";
            user.OTPdateTime = DateTime.Now;

            IdentityResult result = await userManager.UpdateAsync(user);
            if (result.Succeeded)
            {
                Console.WriteLine("Success");
            }
            email.From.Add(new MailboxAddress("TEST", _config["Gmail:Email"]));
            email.To.Add(new MailboxAddress("User", user.Email));
            email.Subject = "Authentication";
            email.Body = new TextPart("plain") { Text = otp };

            using (var smtp = new SmtpClient())
            {
                smtp.Connect("smtp.gmail.com", 587, false);
                smtp.Authenticate(_config["Gmail:Email"], _config["Gmail:AppPassword"]);
                smtp.Send(email);
                smtp.Disconnect(true);
            }
            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.FindByEmailAsync(User.Identity.Name);
                DateTime current = DateTime.Now;
                DateTime otptime = user.OTPdateTime.AddMinutes(15);
                int result = DateTime.Compare(otptime, current);
                if (result < 0)
                {
                    ModelState.AddModelError("", "OTP Token Expired.");
                    return Page();
                }
                if (mfa.code == user.OTP)
                {  
                    user.EmailConfirmed = true;
                    return RedirectToPage("Index");
                }
                else
                {
                    ModelState.AddModelError("code", "Wrong OTP number");
                    return Page();
                }
            }
            return Page();
        }


    }
}

Fresh Farm Market/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Fresh_Farm_Market.Pages
{
    
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Fresh Farm Market/Pages/Changepassword.cshtml
@page
@model Fresh_Farm_Market.Pages.Index1Model
@{
	ViewData["Title"] = "Change Password";
}

<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
<form asp-action="OnPostAsync">
    <div asp-validation-summary="All" class="text-danger"></div>
				<div class="mb-3">
					<label class="form-label" asp-for="Changepassword.EmailAddress">Email Address</label>
					<input type="Text" asp-for="Changepassword.EmailAddress" class="form-control" />
					<span asp-validaton-for="Changepassword.EmailAddress" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Submit</button>
				</div>

    </form>

	</div>
	</div>
	</div>

Fresh Farm Market/Pages/Google.cshtml
@page
@model Fresh_Farm_Market.Pages.GoogleModel
@{
}
<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Google Register </h1>

			<form method="post" enctype="multipart/form-data">
				<div asp-validation-summary="All" class="text-danger"></div>

				<div class="mb-3">
					<label class="form-label" asp-for="GoogleRegister.CreditCard">Credit Card</label>
					<input type="Text" asp-for="GoogleRegister.CreditCard" class="form-control" />
					<span asp-validaton-for="GoogleRegister.CreditCard" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label class="form-label" asp-for="GoogleRegister.PhoneNumber">Phone Number</label>
					<input type="tel" asp-for="GoogleRegister.PhoneNumber" class="form-control" />
					<span asp-validaton-for="GoogleRegister.PhoneNumber" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label class="form-label" asp-for="GoogleRegister.Address">Address</label>
					<input type="Text" asp-for="GoogleRegister.Address" class="form-control" />
					<span asp-validaton-for="GoogleRegister.Address" class="text-danger"></span>
				</div>

				<div class="row mb-3">
				<label class="col-sm-2 col-form-label" asp-for="GoogleRegister.Gender"></label>
			<div class="col-sm-10 d-flex align-items-center">
				<div class="form-check form-check-inline">
							@Html.RadioButtonFor(m => m.GoogleRegister.Gender, "M", new {@class = "form-check-input"})
							<label class="form-check-label">Male</label>
						</div>
						<div class="form-check form-check-inline">
							@Html.RadioButtonFor(m => m.GoogleRegister.Gender, "F", new {@class = "form-check-input"})
							<label class="form-check-label">Female</label>
						</div>
						<span asp-validation-for="GoogleRegister.Gender" class="text-danger"></span>
					</div>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="GoogleRegister.Photo">Photo</label>
					<input type="file" asp-for="GoogleRegister.Photo" class="form-control" accept="image/jpg" />
					<span asp-validaton-for="GoogleRegister.Photo" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label class="form-label" asp-for="GoogleRegister.AboutMe">About Me</label>
					<input type="Text" asp-for="GoogleRegister.AboutMe" class="form-control" />
					<span asp-validaton-for="GoogleRegister.AboutMe" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Register</button>
				</div>
				</form>
				</div>
			</div>
		</div>

Fresh Farm Market/Pages/GoogleUser.cshtml
@page
@model Fresh_Farm_Market.Pages.GoogleUserModel
@{
}

<h1>Only Google User can see this page</h1>

Fresh Farm Market/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<p>
    Email: @Model.user.Email
</p>
<p>
    Credit Card: @Model.user.CreditCard
</p>
<p>
    Gender: @Model.user.Gender
</p>
<p>
    Address: @Model.user.Address
</p>
<p>
    About Me: @Model.user.AboutMe
</p>
<p>
    Phone Number: @Model.user.PhoneNumber
</p>
<img src="@Model.imgsrc" />


<script>
    var options = new CookieOptions { HttpOnly = true };
    var identifier = Guid.NewGuid().ToString();
    Response.Cookies.Append("identifier", identifier, options);

</script>

Fresh Farm Market/Pages/Login.cshtml
@page
@model Fresh_Farm_Market.Pages.LoginModel
@{
}
<script src="https://www.google.com/recaptcha/api.js?render=6LdZTQAkAAAAAIotNBIJyHuDvddb-QOQLvhk8er-"></script>
<script src="https://www.google.com/recaptcha/api.js"></script>
<script>
	grecaptcha.ready(function () {
		grecaptcha.execute('6LdZTQAkAAAAAIotNBIJyHuDvddb-QOQLvhk8er-', { action: 'submit' }).then(function (token) {
			// Add your logic to submit to your backend server here.
			console.log(token);
			$("#input-token").val(token);
		});
	});

</script>

<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Login </h1>
			
			<form id="demo-form" asp-action="OnPostAsync">
				@Html.AntiForgeryToken()
				<button  class="btn btn-light ml-5 border-dark" asp-page-handler="LoginG">Google Login</button>
				<div asp-validation-summary="All" class="text-danger"></div>
				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Email">Email Address</label>
					<input type="Text" asp-for="LModel.Email" class="form-control" />
					<span asp-validaton-for="LModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Password">Password</label>
					<input type="Text" asp-for="LModel.Password" class="form-control" />
					<span asp-validaton-for="LModel.Password" class="text-danger"></span>
					<a href="/changepassword">Forget Password?</a>
				</div>

				<div class="mb-3 form-check">
					<input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
					<label class="form-check-label" asp-for="LModel.RememberMe">Remember Me?</label>
				</div>
				
				

				<input id="input-token" asp-for="LModel.token"  hidden/>
				<span asp-validaton-for="LModel.token" class="text-danger"></span>
				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Login</button>
				</div>
			</form>
		</div>
	</div>
</div>

Fresh Farm Market/Pages/Logout.cshtml
@page
@model Fresh_Farm_Market.Pages.LogoutModel
@{
}
<form method="post">
	<div class="container mt-5">
		<div class="row justify-content-center">
			<div class="col-sm-12 col-md-12 col-lg-4">
				<p> Are you sure you want to logout? </p>
				<p>
					<button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
					<button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
				</p>
			</div>
		</div>
	</div>
</form>

Fresh Farm Market/Pages/MFA.cshtml
@page
@model Fresh_Farm_Market.Pages.Mfa
@{
}
<h1> Verify your account with Email</h1>
<h2>Code sent through Email</h2>

<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			

			<form method="post">
				<div asp-validation-summary="All" class="text-danger"></div>

				<div class="mb-3">
					<label class="form-label" asp-for="mfa.code">Code</label>
					<input type="Text" asp-for="mfa.code" class="form-control" />
					<span asp-validaton-for="mfa.code" class="text-danger"></span>
					<button asp-page-handler="Resend" class="btn btn-outline-info">Resend OTP</button>
				</div>
				
				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Verify</button>
				</div>
		</form>
		</div>
	</div>
</div>

Fresh Farm Market/Pages/Register.cshtml
@page
@model Fresh_Farm_Market.Pages.RegisterModel
@{
}
<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Register </h1>

			<form method="post" enctype="multipart/form-data">
				<div asp-validation-summary="All" class="text-danger"></div>

				<div class="mb-3">
					<label class="form-label" asp-for="rmodel.Email">Email Address</label>
					<input type="Text" asp-for="rmodel.Email" class="form-control" required />
					<span asp-validaton-for="rmodel.Email" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label class="form-label" asp-for="rmodel.Name">Name</label>
					<input type="Text" asp-for="rmodel.Name" class="form-control" required />
					<span asp-validaton-for="rmodel.Name" class="text-danger"></span>
				</div>
				<div class="mb-3">
				@*	<label for="ccn">Credit Card Number:</label>
					<input id="ccn" type="tel" inputmode="numeric" pattern="[0-9\s]{13,19}" autocomplete="cc-number" maxlength="19" placeholder="xxxx xxxx xxxx xxxx">
				*@	<label class="form-label" asp-for="rmodel.CreditCard">Credit Card</label>
					<input type="" asp-for="rmodel.CreditCard" class="form-control" required />
					<span asp-validaton-for="rmodel.CreditCard" class="text-danger"></span>
				</div>
				<div class="row mb-3">
					<label class="col-sm-2 col-form-label" asp-for="rmodel.Gender"></label>
					<div class="col-sm-10 d-flex align-items-center">
						<div class="form-check form-check-inline">
							@Html.RadioButtonFor(m => m.rmodel.Gender, "M", new {@class = "form-check-input"})
							<label class="form-check-label">Male</label>
						</div>
						<div class="form-check form-check-inline">
							@Html.RadioButtonFor(m => m.rmodel.Gender, "F", new {@class = "form-check-input"})
							<label class="form-check-label">Female</label>
						</div>
						<span asp-validation-for="rmodel.Gender" class="text-danger"></span>
					</div>
				</div>
				<div class="mb-3">
					<label class="form-label" asp-for="rmodel.PhoneNumber">Phone Number</label>
					<input type="tel" asp-for="rmodel.PhoneNumber" class="form-control" required />
					<span asp-validaton-for="rmodel.PhoneNumber" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label class="form-label" asp-for="rmodel.Address">Address</label>
					<input type="Text" asp-for="rmodel.Address" class="form-control" required/>
					<span asp-validaton-for="rmodel.Address" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label class="form-label" asp-for="rmodel.Photo">Photo</label>
					<input type="file" asp-for="rmodel.Photo" class="form-control" accept="image/jpg" required />
					<span asp-validaton-for="rmodel.Photo" class="text-danger"></span>
				</div>
				<div class="mb-3">
					<label class="form-label" asp-for="rmodel.AboutMe">About Me</label>
					<input type="Text" asp-for="rmodel.AboutMe" class="form-control" required />
					<span asp-validaton-for="rmodel.AboutMe" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="rmodel.Password">Password</label>
					<input type="Text" asp-for="rmodel.Password" class="form-control" required />
					<span asp-validaton-for="rmodel.Password" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="rmodel.ConfirmPassword">Confirm Password</label>
					<input type="Text" asp-for="rmodel.ConfirmPassword" class="form-control" required />
					<span asp-validaton-for="rmodel.ConfirmPassword" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Register</button>
				</div>
			</form>
		</div>
	</div>
</div>

Fresh Farm Market/Pages/ResetPassword.cshtml
@page
@model Fresh_Farm_Market.Pages.ResetPasswordModel
@{
}
<div class="container mt-5">

    <div class="row justify-content-center align-items-center">

        <div class="col-sm-12 col-md-12 col-lg-4">
<form method="post">
    <div asp-validation-summary="All" class="text-danger">

    </div>

    <input asp-for="resetpassword.Token" type="hidden"/>
    <input asp-for="resetpassword.Email" type="hidden"/>
    <div class="form-group">
        <label asp-for="resetpassword.Password"></label>
        <input asp-for="resetpassword.Password" class="form-control" />
        <span asp-validation-for="resetpassword.Password" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="resetpassword.CfmPassword"></label>
        <input asp-for="resetpassword.CfmPassword" class="form-control" />
        <span asp-validation-for="resetpassword.CfmPassword" class="text-danger"></span>
    </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Reset</button>
                </div>

</form>
</div>
    </div>
</div>